### PR TITLE
user saved successfully done

### PR DESCRIPTION
**Pull request by iamadityaaz**
route changed to improve quality code:

> http://localhost:8000/api/auth/signup

Instead of using env file, database url is used directly --  You use your previous .env by changing my code

### CODE REVIEW

**Comment by shu2496** [comment]
no syntax error now, but an error in postman that cant save user in db

**Comment by iamadityaaz** [comment]
Are you sending your body data properly using postman ?

**Comment by iamadityaaz** [comment]
image

**Comment by shu2496** [comment]
Sir now I am able to save the user. Thanks for your time and efforts, I
sucked up you alot

**Comment by iamadityaaz** [comment]
Feel free for help but always be ready to workout by yourself also for it.
Enjoy your learning

**Pull request merged**
